Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Fe             4s            1.17            1.13
                          3p_y            2.00            2.00
                          3p_z            2.00            2.00
                          3p_x            2.00            2.00
                         3d_xy            1.39            1.39
                         3d_yz            1.32            1.33
                        3d_z^2            1.42            1.43
                         3d_xz            1.33            1.34
                    3d_x^2-y^2            1.37            1.38
                         total           14.00           14.00

      2      Fe             4s            1.17            1.13
                          3p_y            2.00            2.00
                          3p_z            2.00            2.00
                          3p_x            2.00            2.00
                         3d_xy            1.39            1.39
                         3d_yz            1.32            1.33
                        3d_z^2            1.42            1.43
                         3d_xz            1.33            1.34
                    3d_x^2-y^2            1.37            1.38
                         total           14.00           14.00

